name: Toolkit-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - gdal
  - scikit-image
  - pyshp
  - fiona
  - shapely
  - poppler<0.62
  - pip:
    - git+https://github.com/geoscixyz/Toolkit.git@master
