name: Toolkit-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - gdal
  - sckit-image
  - pyshp
  - fiona
  - shapely
  - pip:
    - git+https://github.com/geoscixyz/Toolkit.git@master
